name: Testing SSH server workflow

on:
  workflow_dispatch:

jobs:
  sample:
    name: Sample
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Exit code
      run: |
        exit "1

    - name: Start SSH server on failure
      if: ${{ failure() }}
      timeout-minutes: 30
      uses: mdelillo/ssh-server-action@v1.0.0
      with:
        ngrok-authtoken: "${{ secrets.NGROK_AUTH }}"
        ssh-public-key: "${{ secrets.SSH_KEY }}"
